### ISSUE TITLE
Dead branch during gaming

### ISSUE THREAD

**Issue by IvanZhuyf3** [fucusy/gomoku-first-move-always-win#1]
![image](https://user-images.githubusercontent.com/76635310/103161922-21684180-47b7-11eb-8eff-c15dbad7b877.png)
when it comes to this stage of the game, the game stops.

**Comment by fucusy** [comment]
Can you try it one more time? If this is consistent, let me know please

**Comment by xutengwei** [comment]
![1](https://user-images.githubusercontent.com/96641566/147843147-ff258d96-44a4-4ec7-bb3e-c3c1a5c0d7a7.PNG)
![2](https://user-images.githubusercontent.com/96641566/147843149-39b4e0e2-b005-47a2-a12b-1c7af78209c4.PNG)
![3](https://user-images.githubusercontent.com/96641566/147843150-3c96f330-48bf-40bb-b765-af31a28482ab.PNG)
![4](https://user-images.githubusercontent.com/96641566/147843151-57e6c61d-c3e0-4321-a408-01bb0600aa23.PNG)
![5](https://user-images.githubusercontent.com/96641566/147843152-ee093f75-cf5c-4178-97a9-c6407cf349ce.PNG)
![6](https://user-images.githubusercontent.com/96641566/147843153-9e92be1b-0123-4461-914b-2726e3a3ec83.PNG)
![7](https://user-images.githubusercontent.com/96641566/147843155-dfe7fec3-fa8a-4ebb-9481-e86bbab72218.PNG)
![8](https://user-images.githubusercontent.com/96641566/147843156-0a0f512e-7dff-45ed-8592-1a736c47db88.PNG)
![9](https://user-images.githubusercontent.com/96641566/147843158-0b31672e-9524-41fe-9c97-ea89a937fd20.PNG)
![10](https://user-images.githubusercontent.com/96641566/147843159-f47c72f0-b792-435f-978c-259c301d3ff4.PNG)
![11](https://user-images.githubusercontent.com/96641566/147843160-56b0ed4b-9af7-424d-abd4-b1915b892d79.PNG)

**Comment by xutengwei** [comment]
这是一个游戏的bug吗？

**Comment by Richard7020** [comment]
I find a problem today, and I surprise to see that my problem is the same as this.
![image](https://user-images.githubusercontent.com/98682108/151691343-c486b8c2-6b7c-4c92-b3a1-7c87a2b94271.png)
Specifically, it happened in the way as the following picture showed.
![image](https://user-images.githubusercontent.com/98682108/151691544-ce35b181-fee9-4960-895e-83abf18f0b73.png)
It's not hard to win for black in this state. Hope you can solve this strange bug.

**Comment by fucusy** [comment]
@Richard7020 @xutengwei  @IvanZhuyf3 Thanks for reporting this case. This is solved in the above PR, Would you try it again?

**Comment by Richard7020** [comment]
I find a new problem today which seems like a similar problem.
![image](https://user-images.githubusercontent.com/98682108/152308937-0412850a-9ee7-4666-b25f-02dff8fb33b9.png)
It happened in the way as the following picture showed.
![image](https://user-images.githubusercontent.com/98682108/152309013-16d99c12-99aa-456c-8218-a6abd037d085.png)

**Comment by fucusy** [comment]
Thanks, I am taking a look on it.

**Comment by fucusy** [comment]
> I find a new problem today which seems like a similar problem.
> ![image](https://user-images.githubusercontent.com/98682108/152308937-0412850a-9ee7-4666-b25f-02dff8fb33b9.png)
> It happened in the way as the following picture showed.
> ![image](https://user-images.githubusercontent.com/98682108/152309013-16d99c12-99aa-456c-8218-a6abd037d085.png)

@Richard7020 The issue you mentioned have been fixed and deployed. Can you try it again?

Thanks for reporting the bugs, let me know if you find anything wrong.
