### ISSUE TITLE
the AI has no response

### ISSUE THREAD

**Issue by fucusy** [fucusy/gomoku-first-move-always-win#17]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/5172310/206887689-557ba618-5794-4402-85ff-a4d01e41b695.png">

**Comment by xutengwei** [comment]
现在是花月都不走了

**Comment by fucusy** [comment]
谢谢反馈，现在已经处理好了

**Comment by fucusy** [comment]
未来遇到问题欢迎联系我们
